### ISSUE TITLE
Files are missing in file read

### ISSUE THREAD

**Issue by zhangyizhuoduanweiwei** [joaodsmarques/LumberChunker#1]
In the Retrieval_Granularities_Eval file source code, the Project-Gutenberg-Embeddings file that needs to be read is missing. The code cannot run. How to solve this problem?
![微信图片_20240819182505](https://github.com/user-attachments/assets/99c9226f-aede-48b5-a0a7-0b5af887df34)

![微信图片_20240819182505](https://github.com/user-attachments/assets/45efea06-94d7-4863-89b6-a559e7eafea0)

**Comment by joaodsmarques** [comment]
Hi,

You need to make the embeddings first! We did not provide ours since they occupy a lot of space (~60Gbs). We can make some of them available for you to test

**Comment by zhangyizhuoduanweiwei** [comment]
Thank you very much!But how to make the embeddings?Can you teach me ?Then please make some of them available for me to test ,thank you!

**Comment by zhangyizhuoduanweiwei** [comment]
Thank you very much!But how to make the embeddings?Can you teach me ?Then please make some of them available for me to test ,thank you!

**Comment by joaodsmarques** [comment]
Next week we will make the file we used to generate the embeddings available. We will also provide some examples for you to test on.

The embeddings were generated using openAI embeddings:
https://platform.openai.com/docs/guides/embeddings/embedding-models

**Comment by joaodsmarques** [comment]
You have a guide on how we create our embeddings in our huggingface. The difference from this example to the end project is just the type of embeddings used.

https://huggingface.co/datasets/LumberChunker/GutenQA

**Comment by zhangyizhuoduanweiwei** [comment]
> 下周我们将提供用于生成嵌入的文件。我们还将提供一些示例供您测试。
> 
> 嵌入是使用 openAI 嵌入生成的： https://platform.openai.com/docs/guides/embeddings/embedding-models

Hello author, I have been learning your experiments and papers for a long time, but now I have encountered a bottleneck and urgently need your help. When is it convenient for you to provide an example for generating embedded files and testing? Looking forward to your reply!

**Comment by avduarte333** [comment]
Hello, we upload a folder named "Example".
We think you should be able to run for one book as expected!

Note: the embeddings for the propositions are really large (230MB), hence we can't upload them on GitHub. We upload them for you on a Wetransfer link: https://we.tl/t-2q4T7mlIG8
This will only be valid for 7 days!
